development:
  adapter: postgresql
  encoding: unicode
  database: trainprs
  pool: 5
  username: postgres 
  password: calgary1 

test:
  adapter: postgresql
  encoding: unicode
  database: trainprs
  pool: 5
  username: postgres 
  password: calgary1 